for_hanyoung/for_hanyoung/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('wps.urls', namespace='wps')),
    url(r'^member/', include('member.urls', namespace='member')),

    url(r'^reward/', include('reward.urls', namespace='reward')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

for_hanyoung/reward/urls.py
from django.conf.urls import url

from reward import views

urlpatterns = [
    url(r'^main/$', views.reward_main, name='reward_main'),
    url(r'^detail/$', views.reward_detail, name='reward_detail'),
    url(r'^add/$', views.reward_add, name='reward_add'),

]

for_hanyoung/wps/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('^$', views.wps_index, name='wps_index'),
    url('^wps/list/$', views.wps_list, name='wps_list'),
    url('^wps/detail/(?P<student_id>\d+)/$', views.wps_detail, name='wps_detail'),
]

for_hanyoung/reward/models.py
from django.db import models


class Reward(models.Model):
    name = models.CharField(max_length=14, unique=True)

for_hanyoung/reward/views/reward_add.py
from django.shortcuts import redirect
from reward.models import Reward

__all__ = [
    'reward_add',
]


def reward_add(request):
    if request.method == "POST":
        Reward.objects.create(name=request.POST.get('name'))
        return redirect('reward:reward_main')

for_hanyoung/reward/views/reward_detail.py
import datetime
import random
from django.shortcuts import render
from apis.youtube import search


__all__ = [
    'reward_detail',
]


def reward_detail(request):
    if request.method == 'POST':
        num = random.randint(1, 50)
        reward_list = search(request.POST['keyword'])
        reward = reward_list['items'][num]
        return render(request, 'reward/reward_detail.html', {'reward': reward})

for_hanyoung/templates/reward/reward_detail.html
{% extends 'root/base.html' %}

{% block content %}
<div>
<iframe width="1120" height="630" src="https://www.youtube.com/embed/{{reward.id.videoId}}" frameborder="0" allowfullscreen>

</iframe>
</div>
{{reward.snippet.title}}

<a href="{% url 'reward:reward_main' %}" class="btn btn-default btn-primary">뒤로</a>
{% endblock %}

for_hanyoung/templates/reward/reward_main.html
{% extends 'root/base.html'%}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h3>WPS 진행상황</h3>
      <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar"
        aria-valuenow="{{ current_time }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ current_time }}%">
          {{ current_time }}% Complete
        </div>
      </div>

      <h3>오늘 진행상황</h3>
      <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar"
        aria-valuenow="{{ current_time2 }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ current_time2 }}%">
          {% if current_time2 >= 100 %}
            100% Complete
          {% else %}
            {{ current_time2 }}% Complete

          {% endif %}
        </div>
      </div>


      <h3>보상 리스트</h3>
      <div>
        {% for reward in rewards%}
        <form class='keyboard-button' action="{% url 'reward:reward_detail' %}" method="POST">{%csrf_token%}
          <input   type="hidden" name="keyword" value="{{reward.name}}">
          <button type="submit" class="keyword-button btn btn-info"><strong>{{reward.name}}</strong></button>
        </form>
        {% endfor %}

      </div>

      <div>
        <form action="{% url 'reward:reward_add' %}" method="POST">{% csrf_token %}
          <input size='60' type="text" name="name" placeholder="검색어를 올바르게 입력해주세요.">
          <button type="submit" class="btn btn-primary"><strong>추가</strong></button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}