for_hanyoung/for_hanyoung/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('wps.urls', namespace='wps')),
    url(r'^member/', include('member.urls', namespace='member')),

    url(r'^reward/', include('reward.urls', namespace='reward')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

for_hanyoung/member/urls.py
from django.conf.urls import url
from member import views


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

for_hanyoung/reward/urls.py
from django.conf.urls import url

from reward import views

urlpatterns = [
    url(r'^main/$', views.reward_main, name='reward_main'),
    url(r'^detail/$', views.reward_detail, name='reward_detail'),
    url(r'^add/$', views.reward_add, name='reward_add'),

]

for_hanyoung/wps/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('^$', views.wps_index, name='wps_index'),
    url('^wps/list/$', views.wps_list, name='wps_list'),
    url('^wps/detail/(?P<student_id>\d+)/$', views.wps_detail, name='wps_detail'),
]

for_hanyoung/templates/root/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>홍익한영. 어서오세요. 반갑습니다.</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="{% url 'wps:wps_index' %}">
          <img class='navbar-brand' width='60%' src="{% static 'images/brand-logo.png' %}" alt="iazelf">
          <span class="navbar-text">반갑습니다!</span>
        </a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'reward:reward_main' %}">빨리 끝났으면 좋겠다.</a></li>
        <li><a href="{% url 'wps:wps_list' %}">수강생 관리</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'member:login' %}?next={{ request.path }}">로그인</a></li>
        <li><a href="{% url 'member:signup' %}?next={{request.path}}">회원가입</a></li>
        {% else %}
        <p style="color:blue;margin-bottom:0;display:inline-block; padding:15px 0;">{{ request.user.username}}님 반갑습니다.</p>
        <li><a href="{% url 'member:logout' %}?next={{request.path}}">로그아웃</a></li>
        {% endif %}

      </ul>

    </div>
  </nav>

{% block content %}

{% endblock %}
</body>
</html>

for_hanyoung/templates/root/index.html
{% extends 'root/base.html' %}
{% load static %}




{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <h2 class='text-center'>어서오세요. 반갑습니다.</h2>
            <div class="well">
                <p>이 곳은 이한영을 위한, 이한영에 의한, 이한영의 블로그입니다.</p>
                <p>후원금 받습니다.</p>

            </div>
            <img width='100%' src="{% static 'images/brand-logo.png' %}" alt="brand-logo">
        </div>
    </div>
</div>

{% endblock content %}